pip install virtualenv -i https://pypi.tuna.tsinghua.edu.cn/simple/
Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple/
Collecting virtualenv
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/83/22/54b1180756d2d6194bcafb7425d437c3034c4bff92129c3e1e633079e2c4/virtualenv-20.25.0-py3-none-any.whl (3.8 MB)
     |████████████████████████████████| 3.8 MB 28.5 MB/s
Requirement already satisfied: platformdirs<5,>=3.9.1 in ./.local/lib/python3.9/site-packages (from virtualenv) (4.0.0)
Collecting filelock<4,>=3.12.2
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/81/54/84d42a0bee35edba99dee7b59a8d4970eccdd44b99fe728ed912106fc781/filelock-3.13.1-py3-none-any.whl (11 kB)
Collecting distlib<1,>=0.3.7
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/8e/41/9307e4f5f9976bc8b7fea0b66367734e8faf3ec84bc0d412d8cfabbb66cd/distlib-0.3.8-py2.py3-none-any.whl (468 kB)
     |████████████████████████████████| 468 kB 67.9 MB/s
Installing collected packages: filelock, distlib, virtualenv
  WARNING: Value for scheme.platlib does not match. Please report this to <https://github.com/pypa/pip/issues/10151>
  distutils: /home/zhangchunsheng/.local/lib/python3.9/site-packages
  sysconfig: /home/zhangchunsheng/.local/lib64/python3.9/site-packages
  WARNING: Additional context:
  user = True
  home = None
  root = None
  prefix = None
Successfully installed distlib-0.3.8 filelock-3.13.1 virtualenv-20.25.0

virtualenv clip
created virtual environment CPython3.9.17.final.0-64 in 981ms
  creator CPython3Posix(dest=/data/home/zhangchunsheng/clip, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/data/home/zhangchunsheng/.local/share/virtualenv)
    added seed packages: pip==23.3.1, setuptools==69.0.2, wheel==0.42.0
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator

python -m clip_score 5f86fa77111edb5389b46f5bbd3fcd08_test.jpg 1_2_1_00002_.png --real_flag img --fake_flag img
Loading CLIP model: ViT-B/32
100%|███████████████████████████████████████| 338M/338M [00:14<00:00, 24.3MiB/s]
Traceback (most recent call last):
  File "/usr/lib64/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib64/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/data/home/zhangchunsheng/clip/lib/python3.9/site-packages/clip_score/__main__.py", line 3, in <module>
    clip_score.clip_score.main()
  File "/data/home/zhangchunsheng/clip/lib/python3.9/site-packages/clip_score/clip_score.py", line 212, in main
    dataset = DummyDataset(args.real_path, args.fake_path,
  File "/data/home/zhangchunsheng/clip/lib/python3.9/site-packages/clip_score/clip_score.py", line 89, in __init__
    self.real_folder = self._combine_without_prefix(real_path)
  File "/data/home/zhangchunsheng/clip/lib/python3.9/site-packages/clip_score/clip_score.py", line 144, in _combine_without_prefix
    for name in os.listdir(folder_path):
NotADirectoryError: [Errno 20] Not a directory: '5f86fa77111edb5389b46f5bbd3fcd08_test.jpg'

python -m clip_score a b --real_flag img --fake_flag img
Loading CLIP model: ViT-B/32
Calculating CLIP Score:
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.60it/s]
CLIP Score:  47.78722381591797
